services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:wdMlLcdCVT5zFDxQEGGRWtZhTHKIGBogsAsNko2TBAk=
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    platform: linux/amd64 # Добавляем поддержку для ARM (Mac M1/M2)
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    platform: linux/amd64 # Добавляем поддержку для ARM
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
  scheduler:
    image: weather-microservice-app
    container_name: laravel_scheduler
    depends_on:
      - app
    command: [ "sh", "-c", "while true; do php /var/www/artisan schedule:run; sleep 60; done" ]
    restart: always
    networks:
      - laravel_network
      
networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
